title: "Mazen's Personal Page"
description: "A collection of my research, code projects and random thoughts."
baseurl: ""
url: "https://mazenali.github.io"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
